# Generated by Django 3.0.2 on 2020-02-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chioce_text',
            new_name='choice_text',
        ),
    ]
